services:
  adote-facil-postgres:
    image: postgres:14-alpine
    container_name: 'adote-facil-postgres'
    env_file:
      - ./backend/.env
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_CONTAINER_PORT: ${POSTGRES_CONTAINER_PORT:-5432}

    ports:
      - "${POSTGRES_CONTAINER_PORT:-5432}:5432"

    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - adote-facil-network

  adote-facil-backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: 'adote-facil-backend'
    ports:
      - "8080:8080"
    environment:
      - NODE_ENV=production
    depends_on:
      - adote-facil-postgres
    networks:
      - adote-facil-network

  adote-facil-frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: 'adote-facil-frontend' 
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
    depends_on:
      - adote-facil-backend
    networks:
      - adote-facil-network

volumes:
  db_data:

networks:
  adote-facil-network:
    driver: bridge


# services:
#   adote-facil-postgres:
#     image: postgres:14-alpine
#     container_name: 'adote-facil-postgres'
#     env_file:
#       - ./backend/.env
#     environment:
#       POSTGRES_USER: ${POSTGRES_USER}
#       POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
#       POSTGRES_DB: ${POSTGRES_DB}
#     ports:
#       - "5432:5432"
#     volumes:
#       - db_data:/var/lib/postgresql/data
#     networks:
#       - adote-facil-network
#     healthcheck:
#       test: ["CMD-SHELL", "pg_isready -U postgres"]
#       interval: 5s
#       timeout: 5s
#       retries: 5

#   adote-facil-backend:
#     build:
#       context: ./backend
#       dockerfile: Dockerfile
#     container_name: 'adote-facil-backend'
#     ports:
#       - "8080:8080"
#     environment:
#       - NODE_ENV=production
#       - DATABASE_URL=postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@adote-facil-postgres:5432/${POSTGRES_DB}?schema=public
#     depends_on:
#       adote-facil-postgres:
#         condition: service_healthy
#     networks:
#       - adote-facil-network
#     command: ["./wait-for-it.sh", "adote-facil-postgres:5432", "--", "npm", "run", "start"]

#   adote-facil-frontend:
#     build:
#       context: ./frontend
#       dockerfile: Dockerfile
#     container_name: 'adote-facil-frontend'
#     ports:
#       - "3000:3000"
#     environment:
#       - NODE_ENV=production
#     depends_on:
#       - adote-facil-backend
#     networks:
#       - adote-facil-network

# volumes:
#   db_data:

# networks:
#   adote-facil-network:
#     driver: bridge
