describe('Editar email do usuario', () => {
    it('Cenário Principal - Editar dados', () => {
        cy.loginAdotante()
        cy.get('.sc-26506e6-5 > .sc-c7cdb42d-0 > [href="/area_logada/editar_dados"] > .sc-c7cdb42d-1').click()
        cy.get('[name="email"]').clear()
        cy.get('[name="email"]').type('adotante@adotanteemail.com')
        cy.get('.sc-4bc09f58-3 > .sc-ea747762-0').click()
        cy.get('.sc-26506e6-5 > .sc-c7cdb42d-0 > :nth-child(6)').click()
        cy.visit('http://localhost:3000/login')
        cy.get('[name="email"]').type('adotante@adotanteemail.com')
        cy.get('[name="password"]').type('adotanteaf')
        cy.get('button[type="submit"]').click()
        cy.get('.sc-26506e6-5 > .sc-c7cdb42d-0 > [href="/area_logada/editar_dados"] > .sc-c7cdb42d-1').click()
        cy.get('[name="email"]').clear()
        cy.get('[name="email"]').type('adotante@adotante.com')
        cy.get('.sc-4bc09f58-3 > .sc-ea747762-0').click()
        cy.get('.sc-26506e6-5 > .sc-c7cdb42d-0 > :nth-child(6)').click()
    })

    it('Cenário alternativo - Editar dados e deixar email vazio', () =>{
        cy.loginAdotante()
        cy.get('.sc-26506e6-5 > .sc-c7cdb42d-0 > [href="/area_logada/editar_dados"] > .sc-c7cdb42d-1').click()
        cy.get('[name="email"]').clear()
        cy.get('.sc-4bc09f58-3 > .sc-ea747762-0').click()
        cy.contains('O email é obrigatório')
    })

    it('Cenário alternativo - Editar dados com email inválido', () =>{
        cy.loginAdotante()
        cy.get('.sc-26506e6-5 > .sc-c7cdb42d-0 > [href="/area_logada/editar_dados"] > .sc-c7cdb42d-1').click()
        cy.get('[name="email"]').clear()
        cy.get('[name="email"]').type(' ')
        cy.get('.sc-4bc09f58-3 > .sc-ea747762-0').click()
        cy.contains('Email inválido')
    })
})