name: CI/CD Pipeline

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

# Impede múltiplos pushes seguidos: 
concurrency:
  group: ci-${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true  

# Analisar o tráfego: se houve mudanças no front, back e integração (docker), para rodar apenas os jobs necessários
jobs:
  changes:
    name: Detect changed paths
    runs-on: ubuntu-latest
    outputs:
      backend: ${{ steps.filter.outputs.backend }}
      frontend: ${{ steps.filter.outputs.frontend }}
      integration: ${{ steps.filter.outputs.integration }}
    steps:
      - uses: actions/checkout@v4 # Baixa o repositório
        with:
          fetch-depth: 0 # Baixa o histórico completo para comparar e verificar se houve mudanças

      - name: Filter paths
        id: filter
        uses: dorny/paths-filter@v3 # Action para detectar mudanças em arquivos
        with:
          filters: | # Gatilhos de filtros para identificar se houve mudanças
            backend:
              - 'backend/**'
              - 'docker-compose.yml'
              - '.github/workflows/**'
            frontend:
              - 'frontend/**'
              - 'docker-compose.yml'
              - '.github/workflows/**'
            integration:
              - 'backend/**'
              - 'frontend/**'
              - 'docker-compose.yml'
              - '.github/workflows/**'

  # JOB BACKEND
  backend-check:
    name: Backend Quality
    runs-on: ubuntu-latest
    needs: changes
    # Só roda se houver mudanças na pasta backend ou arquivos de config do workflow
    if: needs.changes.outputs.backend == 'true'
    
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Node (Backend)
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: backend/package-lock.json
          
        # Instalação das dependências garantindo versões exatas e ambiente limpo
      - name: Install Backend Deps
        working-directory: ./backend
        run: npm ci
        
        # Gera os tipos de banco de dados do Prisma antes de compilar ou rodar os testes, para evitar erros de tipagem
      - name: Prisma Generate
        working-directory: ./backend
        run: npm run generate

        # Verifica erros de lint (estilo e boas práticas)
      - name: Lint Check
        working-directory: ./backend
        run: npm run lint

        # Verifica erros de sintaxe e tipagem no código
      - name: Build Check (TS)
        working-directory: ./backend
        run: npm run build

        # Roda os testes unitários
      - name: Unit Tests
        working-directory: ./backend
        run: npm run test:coverage

  # JOB FRONTEND
  frontend-check:
    name: Frontend Quality
    runs-on: ubuntu-latest
    needs: changes
    # Só roda se houver mudanças na pasta frontend
    if: needs.changes.outputs.frontend == 'true'
    
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Node (Frontend)
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: frontend/package-lock.json
        
        # Instalação das dependências garantindo versões exatas e ambiente limpo 
      - name: Install Frontend Deps
        working-directory: ./frontend
        run: npm ci
        
        # Verifica erros de lint (estilo e boas práticas)
      - name: Lint Check
        working-directory: ./frontend
        run: npm run lint

        # Verifica erros de sintaxe e tipagem no código
      - name: Build Check
        working-directory: ./frontend
        run: npm run build
        env:
          NEXT_TELEMETRY_DISABLED: 1

  # JOB INTEGRAÇÃO (Docker)
  integration-test:
    name: Docker Integration
    runs-on: ubuntu-latest
    needs: [changes, backend-check, frontend-check]
 # Espera os jobs anteriores finalizarem
    # Roda sempre, mas usa 'always()' para garantir que não pule se um dos jobs anteriores foi "skipped" propositalmente (ex: mudou só frontend)
    if: >
      needs.changes.outputs.integration == 'true' &&
      (needs.backend-check.result == 'success' || needs.backend-check.result == 'skipped') &&
      (needs.frontend-check.result == 'success' || needs.frontend-check.result == 'skipped')
    
    steps:
      - uses: actions/checkout@v4

        # Cria o arquivo .env necessário para o docker-compose
      - name: Create .env file
        working-directory: ./backend
        run: |
          cat > .env << 'EOF'
          POSTGRES_USER=postgres
          POSTGRES_PASSWORD=postgres
          POSTGRES_DB=adote_facil
          PORT=8080
          EOF
          # --> OUTRA OPÇÃO: GitHub Secrets para definir valores de variáveis sensíveis (configurável no GitHub)
          # --> Pode ser adicionada aqui outras variáveis que forem necessárias...

      - name: Smoke Test (Docker Compose)
        run: |
          # --> Sobe o banco
          docker compose up -d adote-facil-postgres
          sleep 10
          
          # --> Sobe Backend e Frontend (Buildando as imagens novas)
          docker compose up -d --build adote-facil-backend adote-facil-frontend
          
          # --> Verifica status
          docker compose ps
          
          # --> Checa se o Backend está rodando
          backend_running="$(docker inspect -f '{{.State.Running}}' adote-facil-backend 2>/dev/null || echo false)"
          if [ "$backend_running" != "true" ]; then
            echo "Backend falhou."
            docker logs adote-facil-backend || true
            exit 1
          fi

          # --> Checa se o Frontend está rodando
          frontend_running="$(docker inspect -f '{{.State.Running}}' adote-facil-frontend 2>/dev/null || echo false)"
          if [ "$frontend_running" != "true" ]; then
            echo "Frontend falhou."
            docker logs adote-facil-frontend || true
            exit 1
          fi
          
          echo "Todos os serviços subiram com sucesso!"

        # Garante que os containers sejam derrubados mesmo se o teste falhar, evitando que fiquem rodando e consumindo recursos
      - name: Cleanup Docker Compose
        if: always()
        run: docker compose down -v --remove-orphans

  # JOB PUBLICAÇÃO (CD)
  # Só roda se for PUSH na MAIN e se os testes passaram:
  publish-images:
    name: Push to DockerHub
    needs: integration-test # Só excueta se o job de integração passou
    runs-on: ubuntu-latest
    # Só publica se estiver na main - evitando que imagens apenas para testes passem
    if: github.ref == 'refs/heads/main' && github.event_name == 'push' && needs.integration-test.result == 'success'
    steps:
      - uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up Docker Buildx # Para builds mais avançados e multiplataforma
        uses: docker/setup-buildx-action@v3

      # Build e Push do Backend
      - name: Build and push Backend
        uses: docker/build-push-action@v5
        with:
          context: ./backend
          file: ./backend/Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/adote-facil-backend:latest

      # Build e Push do Frontend
      - name: Build and push Frontend
        uses: docker/build-push-action@v5
        with:
          context: ./frontend
          file: ./frontend/Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/adote-facil-frontend:latest